import { CURRENT_PROFILE } from '../data/people.js';
import { MY_FOLLOWS_SEED, NOTIFICATIONS_SEED } from '../data/seeds.js';
import { P4_USERS_SEED, MANAGED_LISTS_SEED, TAGS_SEED, GATE_RULES_SEED } from '../data/admin.js';

/**
 * מצב הפתיחה של הדמו. כל מסך מושך מכאן את מה שהוא צריך, וכל פעולה מחזירה טלאי
 * למצב הזה. השדות בראש הרשימה (screenLoading, bootLoading) הם היחידים שנוספו
 * מעבר לאב-הטיפוס המקורי, והם מזינים את שלדי הטעינה.
 */
export function initialState() {
  return {
    bootLoading: true,
    screenLoading: false,
    activeScreenId: 'catalog',
    viewMode: 'grid',
    searchInput: '',
    searchQuery: '',
    filtersOpen: false,
    typeFilters: [],
    domainFilters: [],
    tagFilters: [],
    selectedItemId: null,
    activeGalleryIndex: 0,
    showAllInterested: false,
    ownerInfoOpen: false,
    contactInfoOpen: false,
    statusInfoOpen: false,
    detailBackScreen: 'catalog',
    detailBackLabel: 'קטלוג',
    shareCopiedFlash: false,
    interestFormOpen: false,
    interestForm: { phone: CURRENT_PROFILE.phone, need: '', classification: '', readyForTrials: false, notes: '' },
    interestFormErrors: {},
    interestFormSubmitAttempted: false,
    interestJustSubmitted: false,
    myFollows: MY_FOLLOWS_SEED.map(f => ({ ...f })),
    followsSort: null,
    followEditingId: null,
    followEditForm: null,
    followEditErrors: {},
    followEditSubmitAttempted: false,
    followRemoveConfirmId: null,
    highlightFollowId: null,
    notifications: NOTIFICATIONS_SEED.map(n => ({ ...n })),
    notifSortKey: null,
    notifSortDir: 'asc',
    sidebarCollapsed: false,

    currentPersona: 'P1',
    expandedNavId: null,
    activeMyItemsTab: 'items',
    myItemsSort: null,
    interestListSort: null,
    pendingSort: null,
    whoInterestedItemId: null,
    whoReadyOnly: false,
    whoNeedExpanded: {},
    approvedIds: [],
    returnedIds: [],
    pendingUI: {},
    editMode: false,
    editDraft: null,
    itemOverrides: {},
    detailContext: 'default',
    detailBackTab: null,
    detailConfirmOpen: false,
    detailNoteOpen: false,
    detailNoteText: '',
    detailNoteError: false,
    addItemTab: 'form',
    formMode: null,
    formSourceId: null,
    itemForm: null,
    formErrors: {},
    formSubmitAttempted: false,
    formSavedFlash: false,
    formPreviewOpen: false,
    tagInput: '',
    batch: { fileName: null, checked: false, report: null, invalidState: false, corrections: {}, confirmOpen: false, importedFlash: false },

    myTasksTab: 'reminders',
    reminderClosed: {},
    p3CanPublish: false,

    p4Users: P4_USERS_SEED.map(u => ({ ...u })),
    p4UsersCreateOpen: false,
    p4UserForm: null,
    p4UsersEditingId: null,
    p4ApproversTab: 'all',
    p4ApproverAddOpen: false,
    p4UserDetailId: null,
    p4TransferOutgoingId: '',
    p4TransferIncomingId: '',
    p4TransferConfirmOpen: false,
    p4TransferSimulateFailure: false,
    p4TransferResult: null,
    p4ManagedListsTab: 'values',
    p4SelectedListId: 'body',
    p4Lists: MANAGED_LISTS_SEED.map(l => ({ ...l, values: l.values.map(v => ({ ...v })) })),
    p4ListNewValueInputs: {},
    p4TagFilter: '',
    p4Tags: TAGS_SEED.map(t => ({ ...t })),
    p4TagMergeOpenName: null,
    p4TagMergeTarget: '',
    p4LogActionType: '', p4LogUser: '', p4LogItem: '',
    p4GateRules: GATE_RULES_SEED.map(g => ({ ...g })),
    rowUI: {}
  };
}
